# Generated by Django 5.2.4 on 2025-07-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_edad_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
    ]
